#!/bin/bash

BOOKMARK_DIR="$XDG_CONFIG_HOME"/bookmarks

ls $BOOKMARK_DIR | dmenu -i -l 5 -fn "Monospace-10:normal" -x 20 -y 20 -dim "0.6" -w 1880 | xargs -r -I '{}' sh -c "echo '$1 $QUTE_URL' >> $BOOKMARK_DIR/'{}'"
