#!/bin/sh

BOOKMARK_DIR="$HOME"/Nextcloud/bookmarks

category=$(ls $BOOKMARK_DIR | rofi -dmenu -i -p "Category")
cat $BOOKMARK_DIR/"$category" | rofi -dmenu -i -p "Bookmark" | awk '{print $2}' | xargs -I '{}' $BROWSER '{}' & disown
